// multipath pipeline for jenkins and docker check 
pipeline {
    agent any
    stages {
        stage('Check Docker') {
            steps {
                sh '''
                    echo "PATH=$PATH"
                    which docker
                    docker --version
                '''
            }
        }
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t team-skeleton:${BUILD_NUMBER} .'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -B test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
